#!/usr/bin/env bash
# Install ngnix web server and configure redirects

apt-get -y update
apt-get -y install nginx

echo 'Hello World!' > /var/nginx/html/index.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root /etc/nginx/html;
    index index.html index.htm;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4
    }
}" > /etc/nginx/site-available/default

service ngnix start
